### PR TITLE
[FIX] podio bug 47 - fix IE11 bug with unresponsive images in Text & …

### PR DESCRIPTION
**Pull request by pxamike**
…Media-elements.

Successfully tested in latest IE11 in Win7 and Win8.1

### CODE REVIEW

**Comment by phathoang** [comment]
JS looks scary to me and someone might spend hours to debug why something is different in only IE11 when this fails. It also adds inline css which is hard to override.

**Comment by pxamike** [comment]
What would you suggest?

**Review by dmh — CHANGES_REQUESTED** [review]
It is TYPO3 (fluid_styled_content) bug, so not sure that we should fix it using this way. Maybe we should leave it like it is now, without fixing. Not sure that somebody will scale screen to mobile view in IE11.

**Comment by dmh** [comment]
#31

**Pull request closed without merging**
