### PR TITLE
[FIX]  Text & Media-images are not responsively scaling in IE11 (Podio bug47)

### PR DESCRIPTION
**Pull request by yar-trach**
Dmytro "I think we should leave it like it is now, without fixing. Not sure that somebody will scale screen to mobile view in IE11."

We found this bug even not in mobile size of IE - if this image in sidebar, or in small column (col-md-3) we will get same bug.

### CODE REVIEW

**Comment by pxamike** [comment]
ie11_without_and_with_suggested_fix

The problem with this fix (which is css-based) is that while it fixes the responsiveness of the image it breaks the correct caption-behaviour. See attached image (left is without fix and right is with fix applied). You can look at the elements in the bottom of http://www.t3kit.com/content/typical-page-content/text-media/ To my knowledge it's not possible to fix this using css, which is why my suggestion ultimately became a javascript-based one. Also, it would be better to use .ie11-class instead of .IE imho.

**Comment by jozefspisiak** [comment]
Great comment @pxamike , @rozmathplus can you implement these changes as suggested?

**Comment by dmh** [comment]
#6

**Comment by pxamike** [comment]
Also, please don't have different solutions in felayout_t3kit and felayout_bluemountain - I just saw this commit in master branch which contains the CSS-fix.

https://github.com/t3kit/felayout_t3kit/commit/dca83ea21da618b130190beb812f3d5bafceec18

It should be the same solution in both.

**Comment by dmh** [comment]
Yes, I agree. This was a little bit wrong commit because it consists of two different fixes. So I will remove code, which you can find below, from master branch until we will have a solution for this bug. Thanks.

```
.IE {
     .ce-gallery,
     .ce-gallery .ce-outer,
     .ce-gallery .ce-inner,
     .ce-gallery .ce-column {
         max-width: 100%;
     }
     .ce-gallery figure,
     .ce-gallery figcaption {
         display: block;
     }
```

**Comment by dmh** [comment]
#31

**Pull request closed without merging**
